---

- name: Delete k3s if already present
  file:
    path: /usr/local/bin/k3s
    state: absent

- name: Download k3s binary
  get_url:                                                           
      url: https://github.com/rancher/k3s/releases/download/v0.2.0/k3s
      dest: /usr/local/bin/k3s
      owner: root
      group: root
      mode: 755
