---
- name: Download k3s binary
  get_url:
    url: https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/{{ bin_arch_map[ansible_architecture] }}
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 755
    force: yes
