name: Unit Test Coverage
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
    - name: Install Go
      uses: actions/setup-go@v2 
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Run Unit Tests
      run: | 
        go test ./pkg/...  -coverprofile coverage.out
        go tool cover -func coverage.out
    - name: Upload Results To Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./coverage.out
        flags: unittests # optional
        verbose: true # optional (default = false)